### ISSUE TITLE
[Feature request] HugoMods module to integrate Kroki diagraming service

### ISSUE THREAD

**Issue by ezzle** [hugomods/kroki#4]
Hi

### Requested Feature
A HugoMods module to support the kroki unified API for diagraming

**Embedding options**

1. image tag (! link and action inside the svg do not work)
2. embeed tag
3. inline svg

**diagram definition options**

1. via data
2. as code block content

### What'is Kroki
`Kroki provides a unified API with support for BlockDiag (BlockDiag, SeqDiag, ActDiag, NwDiag, PacketDiag, RackDiag), BPMN, Bytefield, C4 (with PlantUML), D2, DBML, Ditaa, Erd, Excalidraw, GraphViz, Mermaid, Nomnoml, Pikchr, PlantUML, Structurizr, SvgBob, Symbolator, TikZ, UMLet, Vega, Vega-Lite, WaveDrom, WireViz... and more to come!`
https://kroki.io/

### Third party integration
**Initial shortcode approach from Joe Mooring** 
`Use a fenced code block to embed an SVG image of a diagram in your [Hugo](https://gohugo.io/) site using the free [Kroki](https://kroki.io/) service. Unlike JavaScript solutions that require client-side rendering, this approach embeds an SVG image in your page.`
https://www.veriphor.com/articles/diagrams/
https://www.veriphor.com/articles/diagrams/#source-code

**Inside Perplex Theme**
`This theme includes a codeblock render hook which allows to enhance the diagrams in a similar way as images.`
https://perplex.desider.at/doc/plugin/kroki/

Best regards,

Tshitshi

**Comment by razonyang** [comment]
A simple guide to test and preview the module.

## 1. Import the module

```toml
// hugo.toml
[[module.imports]]
path = "github.com/hugomods/kroki"
```

## 2. Using via Code Block

```markdown
```kroki {_type="graphviz" class="class-one class-two" id="my-kroki-1" data-foo="bar"}
digraph G {Hello->World}
```
```

- `_type`: the diagram type.
- `_output`: `inline` (default) or `embed`.
- You can apply any valid attributes on the diagrams, such as the `class`, `id` and `data-foo`.



## 2. Using via Code Block

```markdown
```kroki {_type="graphviz" _output="embed" class="class-one class-two" id="my-kroki-1" data-foo="bar"}
digraph G {Hello->World}
```
```

- `_type`: the diagram type.
- `_output`: `inline` (default) or `embed`, optional.
- You can apply any valid attributes on the diagrams elements, such as the `class`, `id` and `data-foo`.

## 3. Using via Shortcode

```markdown
{{< kroki _name="diagrams/foo.dot" _type="graphviz" _output="embed" class="x y z" id="xyz" >}}
```

- `_name`: the file name, both of page resource and site resource are supported.
- `_type` as same as code block way.
- `_output` as same as code block way.
- You can also attach any custom attributes.

## 4. Tweak Styles

Both of `<svg>` and `<embed>` elements will have the `.kroki` class name, apply styles on `svg.kroki` and `embed.kroki` to suit your theme's styles.

## About the `<img>` tag.

According to your explainations above, seems we don't need it?

## About release.

Will draft a release once you're satisifed with it.

**Comment by ezzle** [comment]
Thank you.
I am testing  and will inform you

Best regards,

Tshitshi

Le lun. 11 mars 2024 à 14:11, Razon Yang ***@***.***> a
écrit :

**Comment by ezzle** [comment]
Hi Razon, 
Thank you very much.

- [x] **Using via Code Block** works fine. 

- [ ]  **Using via Shortcode**  not working for me. No output on the doc and no error was reported on the console.

Later will create a repo for debugging and share the link.

The current testing just tried to validate that the 2 options are operational. The result: only 1 option is ok for me.

Later, more testing with real-life use cases and in combination with other hugomods modules. Thank you for the excellent work and the extreme reactivity.  

Best regards,  

Tshitshi

**Comment by ezzle** [comment]
**Update : All tests OK**

Tested with real-life use cases and mixing with toggle module : All fine, inclusive with file from page ressource as well as from global ressource.

Good job!

I think you can release a first public version.

Best regards.

Tshitshi

**Comment by razonyang** [comment]
Done, https://github.com/hugomods/kroki/releases/tag/v0.1.0

**Comment by ezzle** [comment]
Thx

Le jeu. 14 mars 2024 à 09:19, Razon Yang ***@***.***> a
écrit :

**Comment by razonyang** [comment]
FYI, docs site is live now https://kroki.hugomods.com/, which provides detailed usages and examples.

**Comment by ezzle** [comment]
Excellent!

Thank you

Tshitshi

Le ven. 15 mars 2024 à 09:45, Razon Yang ***@***.***> a
écrit :
